apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: actions-runner-controller-github-webhook-server
  namespace: actions-runner-system
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-protocol: "http"
spec:
  rules:
  - host: agents.gbabes.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: github-webhook-server
            port:
              number: 80