# runner.yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: gb3s-cluster-msi
spec:
  type: 0
  resourceID: $GB3S_RESOURCEID
  clientID: $GB3S_CLIENTID
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: gb3s-cluster-msi-binding
spec:
  azureIdentity: "gb3s-cluster-msi"
  selector: "gb3s-cluster"
---