# runner.yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: gb3s-cluster-msi
spec:
  type: 0
  resourceID: /subscriptions/4dc1bd33-fef6-413d-aa31-bc639452a449/resourcegroups/gb3s/providers/Microsoft.ManagedIdentity/userAssignedIdentities/gb3s-cluster
  clientID: 340af2c4-3165-46d9-9adf-c24fd21f6873
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: gb3s-cluster-msi-binding
spec:
  azureIdentity: "gb3s-cluster-msi"
  selector: "gb3s-cluster"
---