apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: gb3s-runner
  namespace: actions-runner-system
  labels:
    aadpodidbinding: gb3s-cluster
spec:
  organization: gb3s
  env: []