apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gb3s-runner
  namespace: actions-runner-system
spec:
  organization: gb3s
  replicas: 1
  env: []
  template:
    spec:
      labels: 
        aadpodidbinding: gb3s-cluster