apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: gb3s-runner
  namespace: actions-runner-system
  labels:
spec:
  organization: gb3s
  env: []
  template:
    metadata:
      labels:
        aadpodidbinding: gb3s-cluster