apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gb3s-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:  
    metadata:
      labels: 
        aadpodidbinding: gb3s-cluster
    spec:
      repository: gb3s/gb3scluster
      image: gb3sacr.privatelink.azurecr.io/gb3s/runner:latest
