# runner.yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  namespace: secret-provider-test
  name: gb3s-cluster-msi
spec:
  type: 0
  resourceID: /subscriptions/4dc1bd33-fef6-413d-aa31-bc639452a449/resourcegroups/gb3s/providers/Microsoft.ManagedIdentity/userAssignedIdentities/gb3s-cluster
  clientID: c5e77d8d-6a18-4871-93dc-474c8a084e56
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  namespace: secret-provider-test
  name: gb3s-cluster-msi-binding
spec:
  azureIdentity: "gb3s-cluster-msi"
  selector: "gb3s-cluster"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: gb3s-runner
  namespace: actions-runner-system
spec:
  organization: gb3s
  env: []