apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gb3s-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  env: []
  template:  
    spec:
      organization: gb3s
      metadata:
        labels: 
          aadpodidbinding: gb3s-cluster