apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  namespace: secret-provider-test
  name: gb3s-cluster-msi
spec:
  type: 0
  resourceID: /subscriptions/4dc1bd33-fef6-413d-aa31-bc639452a449/resourcegroups/gb3s/providers/Microsoft.ManagedIdentity/userAssignedIdentities/gb3s-cluster
  clientID: c5e77d8d-6a18-4871-93dc-474c8a084e56
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  namespace: secret-provider-test
  name: gb3s-cluster-msi-binding
spec:
  azureIdentity: "gb3s-cluster-msi"
  selector: "gb3s-cluster"
---
# This is a SecretProviderClass example using aad-pod-identity to access the key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-podid
  namespace: secret-provider-test
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"               # Set to true for using aad-pod-identity to access your key vault
    keyvaultName: gb3s-keyvault       # Set to the name of your key vault
    cloudName: ""                        # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: test1
          objectType: secret             # object types: secret, key, or cert
          objectVersion: ""              # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: test1
          objectType: key
          objectVersion: ""
    tenantId: 90928a04-9c35-4ad8-9b74-f2d225f9b0e9                # The tenant ID of the key vault
---
# This is a sample pod definition for using SecretProviderClass and aad-pod-identity to access the key vault
kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store-inline-podid
  namespace: secret-provider-test
  labels:
    aadpodidbinding: gb3s-cluster                 # Set the label value to the name of your pod identity
spec:
  containers:
    - name: busybox
      image: k8s.gcr.io/e2e-test-images/busybox:1.29-1
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kvname-podid"