name: build_image
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: azure/docker-login@v1
        with:
          login-server: 'gb3sacr.privatelink.azurecr.io.' # default: index.docker.io